language: node_js

node_js:
  - "node"
  - "11.6"

os:
  - linux

env:
  - CODE_VERSION=1.30.0 # Minimal Version
  # - CODE_VERSION=* # Last Stable Version
  # - CODE_VERSION=insiders # Insider Version

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run vscode:prepublish
  # For coverage, disable automatic start of extension
  - sed -i.bak 's/"\*"//g' package.json

script:
  - npm run style-check
  - npm test --silent

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: release
      language: node_js
      node_js: "11.6"
      install:
        - npm install
      script:
        - npm run compile
  allow_failures:
    - env: CODE_VERSION=insiders
